# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1562, 810)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1600, 1000))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.scrollArea.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1525, 773))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(1400, 0))
        self.frame.setMaximumSize(QtCore.QSize(1500, 100))
        self.frame.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"border: 5px ridge  rgb(136, 136, 136) ;\n"
"border-radius: 12px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblMinimalizacja = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMinimalizacja.sizePolicy().hasHeightForWidth())
        self.lblMinimalizacja.setSizePolicy(sizePolicy)
        self.lblMinimalizacja.setMinimumSize(QtCore.QSize(450, 0))
        self.lblMinimalizacja.setMaximumSize(QtCore.QSize(400, 100))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(False)
        font.setKerning(True)
        self.lblMinimalizacja.setFont(font)
        self.lblMinimalizacja.setStyleSheet("background-color: None;\n"
"border: None;\n"
"font: 600 36pt \"Open Sans\";\n"
"")
        self.lblMinimalizacja.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMinimalizacja.setObjectName("lblMinimalizacja")
        self.horizontalLayout_3.addWidget(self.lblMinimalizacja)
        self.lblMetoda = QtWidgets.QLabel(self.frame)
        self.lblMetoda.setMinimumSize(QtCore.QSize(150, 100))
        self.lblMetoda.setMaximumSize(QtCore.QSize(150, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        self.lblMetoda.setFont(font)
        self.lblMetoda.setStyleSheet("background-color: None;\n"
"font: 500 24pt \"Open Sans\";\n"
"border: None")
        self.lblMetoda.setObjectName("lblMetoda")
        self.horizontalLayout_3.addWidget(self.lblMetoda)
        self.lblQuine = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblQuine.sizePolicy().hasHeightForWidth())
        self.lblQuine.setSizePolicy(sizePolicy)
        self.lblQuine.setMinimumSize(QtCore.QSize(600, 70))
        self.lblQuine.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setBold(True)
        font.setItalic(False)
        self.lblQuine.setFont(font)
        self.lblQuine.setStyleSheet("font: 700 45pt \"Script MT Bold\";\n"
"background-color: None;\n"
"border: None")
        self.lblQuine.setObjectName("lblQuine")
        self.horizontalLayout_3.addWidget(self.lblQuine)
        self.label_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(113, 81))
        self.label_2.setMaximumSize(QtCore.QSize(113, 81))
        self.label_2.setBaseSize(QtCore.QSize(0, 0))
        self.label_2.setStyleSheet("border: None;\n"
"background-color: None;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:/OneDrive/Pulpit/kkz3.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout_3.addWidget(self.frame)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_5.setMaximumSize(QtCore.QSize(800, 16777215))
        self.frame_5.setStyleSheet("background-color: None;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.lblSchemat = QtWidgets.QLabel(self.frame_5)
        self.lblSchemat.setGeometry(QtCore.QRect(0, 10, 691, 521))
        self.lblSchemat.setMaximumSize(QtCore.QSize(900, 16777215))
        self.lblSchemat.setStyleSheet("background-color: None;")
        self.lblSchemat.setText("")
        self.lblSchemat.setObjectName("lblSchemat")
        self.btnShow = QtWidgets.QPushButton(self.frame_5)
        self.btnShow.setGeometry(QtCore.QRect(680, 570, 101, 41))
        self.btnShow.setStyleSheet(":active\n"
"{\n"
"font: 500 12pt \"Open Sans\";\n"
"-webkit-border-radius: 12px;\n"
"-moz-border-radius: 12px;\n"
"border-radius: 12px;\n"
"background-color: rgb(15, 111, 198);\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 255, 255)\n"
"}\n"
":!active\n"
"{\n"
"font: 500 12pt \"Open Sans\";\n"
"-webkit-border-radius: 12px;\n"
"-moz-border-radius: 12px;\n"
"border-radius: 12px;\n"
"background-color: rgb(15, 111, 198);\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 255, 255)\n"
"}\n"
"\n"
":disabled\n"
"{\n"
"font: 500 12pt \"Open Sans\";\n"
"-webkit-border-radius: 12px;\n"
"-moz-border-radius: 12px;\n"
"border-radius: 12px;\n"
"background-color: rgb(208, 208, 208);\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 255, 255)\n"
"}\n"
"\n"
"\n"
":pressed\n"
"{\n"
"    background-color: rgb(0, 85, 255);\n"
"    border-style: inset\n"
"}\n"
":hover\n"
" {\n"
"    border: 2px solid rgb(0, 0, 0)\n"
"}\n"
":focus\n"
" {\n"
"    border: 2px solid rgb(0, 0, 255)\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.btnShow.setAutoDefault(True)
        self.btnShow.setObjectName("btnShow")
        self.lblResultMath = QtWidgets.QLabel(self.frame_5)
        self.lblResultMath.setGeometry(QtCore.QRect(260, 580, 341, 41))
        self.lblResultMath.setStyleSheet("border-color: None;")
        self.lblResultMath.setText("")
        self.lblResultMath.setObjectName("lblResultMath")
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        self.label_8.setGeometry(QtCore.QRect(20, 580, 227, 26))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border-color: None;\n"
"font: 500 18pt \"Open Sans\";\n"
"")
        self.label_8.setObjectName("label_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 620, 81, 22))
        self.pushButton_2.setStyleSheet(":active\n"
"{\n"
"font: 500 10pt \"Open Sans\";\n"
"-webkit-border-radius: 12px;\n"
"-moz-border-radius: 12px;\n"
"border-radius: 12px;\n"
"background-color: None;\n"
"color: rgb(0, 0, 0);\n"
"border: 2px solid rgb(208, 208, 208)}\n"
":pressed\n"
"{\n"
"    background-color: rgb(0, 85, 255);\n"
"}\n"
":hover\n"
" {\n"
"    border: 2px solid rgb(0, 0, 0)\n"
"}\n"
":!hover\n"
" {\n"
"    border: 2px solid rgb(208, 208, 208)\n"
"}\n"
"\n"
":released\n"
" {\n"
"    border: 2px solid rgb(208, 208, 208)\n"
"}\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setGeometry(QtCore.QRect(110, 620, 75, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_4.addWidget(self.frame_5, 0, 2, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_4.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_4.setStyleSheet("background-color: None;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border-color: None;\n"
"background-color: None;")
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.tblBinary = QtWidgets.QTableView(self.frame_4)
        self.tblBinary.setStyleSheet("QHeaderView::section\n"
"{\n"
"            border-top:0px solid #D8D8D8;\n"
"            border-left:0px solid #D8D8D8;\n"
"            border-right:1px solid black;\n"
"            border-bottom: 1px solid #D8D8D8;\n"
"            background-color:white;\n"
"            padding:4px;\n"
"            font: 12pt;\n"
"\n"
"}\n"
"\n"
"QTableView {\n"
"        border-collapse: collapse;\n"
"        gridline-color: black;\n"
"        selection-background-color: blue;\n"
"        text-align: center;\n"
"        font: 12pt;\n"
"            border: 3px ridge  rgb(136, 136, 136) ;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"font: 12pt;\n"
"    border-top: None;\n"
"    border-bottom: 2px solid rgb(0, 0, 0);\n"
"    border-collapse: collapse;\n"
"}\n"
"\n"
"QTableCornerButton::section\n"
"{\n"
"            border-top: 0px solid black;\n"
"           border-left: 0px solid black;\n"
"            border-right: 2px solid black;\n"
"            border-bottom: 2px solid black;\n"
"           background-color: white;\n"
"}\n"
"\n"
"QHeaderView::section:vertical\n"
"{\n"
"    font: 10pt;\n"
"    border-top: None;\n"
"    border-bottom: 1px solid ;\n"
"    border-right: 2px solid black;\n"
"    border-collapse: collapse;\n"
"}")
        self.tblBinary.setLineWidth(3)
        self.tblBinary.setObjectName("tblBinary")
        self.gridLayout_6.addWidget(self.tblBinary, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_4, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_2.setStyleSheet("background-color: None;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lnMinterm = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lnMinterm.setFont(font)
        self.lnMinterm.setStyleSheet("border: 3px solid #1C6EA4;\n"
"border-radius: 12px;")
        self.lnMinterm.setText("")
        self.lnMinterm.setFrame(True)
        self.lnMinterm.setAlignment(QtCore.Qt.AlignCenter)
        self.lnMinterm.setDragEnabled(True)
        self.lnMinterm.setObjectName("lnMinterm")
        self.gridLayout_5.addWidget(self.lnMinterm, 2, 2, 1, 3)
        self.lnVariable = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lnVariable.setFont(font)
        self.lnVariable.setStyleSheet("border: 3px solid #1C6EA4;\n"
"border-radius: 12px;")
        self.lnVariable.setInputMask("")
        self.lnVariable.setAlignment(QtCore.Qt.AlignCenter)
        self.lnVariable.setObjectName("lnVariable")
        self.gridLayout_5.addWidget(self.lnVariable, 0, 2, 1, 3)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border-color: None;\n"
"background-color: None;")
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-color: None;\n"
"background-color: None;")
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("border-color: None;\n"
"background-color: None;")
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 1, 1, 2, 1)
        self.tblMinterm = QtWidgets.QTableView(self.frame_2)
        self.tblMinterm.setMaximumSize(QtCore.QSize(300, 16777215))
        self.tblMinterm.setStyleSheet("QTableView {\n"
"        gridline-color: black;\n"
"        selection-background-color: blue;\n"
"        text-align: center;\n"
"        font: 14pt;\n"
"    border: 3px solid #1C6EA4;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QHeaderView\n"
"{\n"
"    font: 600 11pt \"Open Sans\";\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(15, 111, 198);\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 4px;\n"
"    border-style: solid;\n"
"    border-bottom: 1px solid #fffff8;\n"
"    border-right: 1px solid #fffff8;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border-top: None;\n"
"\n"
"}\n"
"\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border-left: 1px solid #fffff8;\n"
"}")
        self.tblMinterm.setObjectName("tblMinterm")
        self.gridLayout_5.addWidget(self.tblMinterm, 9, 1, 1, 4)
        self.chbDontCare = QtWidgets.QCheckBox(self.frame_2)
        self.chbDontCare.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chbDontCare.setFont(font)
        self.chbDontCare.setMouseTracking(True)
        self.chbDontCare.setStyleSheet("border-color: None;\n"
"background-color: None;")
        self.chbDontCare.setText("")
        self.chbDontCare.setObjectName("chbDontCare")
        self.gridLayout_5.addWidget(self.chbDontCare, 5, 0, 1, 1)
        self.lnDontCare = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lnDontCare.setFont(font)
        self.lnDontCare.setStyleSheet(":active\n"
"{\n"
"border: 3px solid #1C6EA4;\n"
"border-radius: 12px;\n"
"}\n"
":disabled\n"
"{\n"
"    \n"
"    background-color: rgb(234, 234, 234);\n"
"    border: 2px solid rgb(172, 172, 172);\n"
"    border-radius: 12px;\n"
"\n"
"}")
        self.lnDontCare.setAlignment(QtCore.Qt.AlignCenter)
        self.lnDontCare.setObjectName("lnDontCare")
        self.gridLayout_5.addWidget(self.lnDontCare, 5, 2, 1, 3)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border-color: None;\n"
"background-color: None;")
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 8, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_5.addItem(spacerItem, 6, 2, 1, 1)
        self.btnFind = QtWidgets.QPushButton(self.frame_2)
        self.btnFind.setMinimumSize(QtCore.QSize(110, 40))
        self.btnFind.setMaximumSize(QtCore.QSize(100, 35))
        self.btnFind.setStyleSheet(":active\n"
"{\n"
"font: 500 12pt \"Open Sans\";\n"
"-webkit-border-radius: 12px;\n"
"-moz-border-radius: 12px;\n"
"border-radius: 12px;\n"
"background-color: rgb(15, 111, 198);\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 255, 255)\n"
"}\n"
":!active\n"
"{\n"
"font: 500 12pt \"Open Sans\";\n"
"-webkit-border-radius: 12px;\n"
"-moz-border-radius: 12px;\n"
"border-radius: 12px;\n"
"background-color: rgb(15, 111, 198);\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 255, 255)\n"
"}\n"
"\n"
"\n"
":pressed\n"
"{\n"
"    background-color: rgb(0, 85, 255);\n"
"    border-style: inset\n"
"}\n"
":hover\n"
" {\n"
"    border: 2px solid rgb(0, 0, 0)\n"
"}\n"
":focus\n"
" {\n"
"    border: 2px solid rgb(0, 0, 255)\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.btnFind.setAutoDefault(True)
        self.btnFind.setObjectName("btnFind")
        self.gridLayout_5.addWidget(self.btnFind, 6, 3, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_5.setBuddy(self.lnVariable)
        self.label_3.setBuddy(self.lnVariable)
        self.label.setBuddy(self.lnMinterm)
        self.label_4.setBuddy(self.lnVariable)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lnMinterm, self.chbDontCare)
        MainWindow.setTabOrder(self.chbDontCare, self.lnDontCare)
        MainWindow.setTabOrder(self.lnDontCare, self.btnFind)
        MainWindow.setTabOrder(self.btnFind, self.tblMinterm)
        MainWindow.setTabOrder(self.tblMinterm, self.tblBinary)
        MainWindow.setTabOrder(self.tblBinary, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.btnShow)
        MainWindow.setTabOrder(self.btnShow, self.scrollArea)
        MainWindow.setTabOrder(self.scrollArea, self.lnVariable)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblMinimalizacja.setText(_translate("MainWindow", "Minimalizacja"))
        self.lblMetoda.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">metodą</p></body></html>"))
        self.lblQuine.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Quine’a-McCluskeya</p></body></html>"))
        self.btnShow.setText(_translate("MainWindow", "Guzik"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Forma zminimalizowana:</span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "TEX"))
        self.pushButton_3.setText(_translate("MainWindow", "Tekst"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Tablica prawdy:</p></body></html>"))
        self.lnMinterm.setPlaceholderText(_translate("MainWindow", "1, 2, 5, 9, 12"))
        self.lnVariable.setText(_translate("MainWindow", "A, B, C, D"))
        self.lnVariable.setPlaceholderText(_translate("MainWindow", "a, b, c, d"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">wartości <br/>nieokreślone</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Zmienne:</p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Mintermy:</p></body></html>"))
        self.lnDontCare.setPlaceholderText(_translate("MainWindow", "0, 6"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Wektory:</p></body></html>"))
        self.btnFind.setText(_translate("MainWindow", "Generuj"))
